version: '3.9'

services:
  web:
    container_name: web
    tty: true
    build:
      context: ..
      dockerfile: ./infrastructure/Dockerfile.front
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    volumes:
      - type: bind
        source: ../front
        target: /app
      - type: bind
        source: ../devops
        target: /app/devops
      

  # api:
  #   container_name: api
  #   image: ${FRONT_API_IMAGE}
  #   build:
  #     context: ..
  #     dockerfile: ./infrastructure/Dockerfile
  #   ports:
  #     - '${API_PORT}:${API_PORT}'
  #   depends_on:
  #     - database
  #   environment:
  #     - POSTGRES_HOST: ${POSTGRES_HOST}
  #     - POSTGRES_USER: ${POSTGRES_USER}
  #     - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     - POSTGRES_PORT: ${POSTGRES_PORT}
  #     - POSTGRES_DB: ${POSTGRES_DB}
  #     - MIGRATION_SEEDERS: ${MIGRATION_SEEDERS}
  #   volumes:
  #     - type: bind
  #       source: ../
  #       target: /app

  # database:
  #   container_name: database
  #   image: ${DATABASE_BASE_IMAGE}
  #   ports:
  #     - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  #   environment:
  #     - POSTGRES_USER: ${POSTGRES_USER}
  #     - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     - POSTGRES_DB: ${POSTGRES_DB}
    
